### PR TITLE
Update check for empty on children

### PR DESCRIPTION
**Pull request by Loque-**

### CODE REVIEW

**Comment by gavinorland** [comment]
The warning comes back with this commit:

```
console.error node_modules/fbjs/lib/warning.js:33
      Warning: Received `false` for a non-boolean attribute `empty`.

      If you want to write it to the DOM, pass a string instead: empty="false" or empty={value.toString()}.

      If you used to conditionally omit it with empty={condition && value}, pass empty={condition ? value : undefined} instead.
          in a (created by Link)
          in Link (created by TotalWrapper)
          in TotalWrapper (created by Item)
          in Item (created by Total)
          in Total
          in div (created by OuterWrapper)
          in OuterWrapper (created by CounterBar)
          in CounterBar
          in Router (created by HashRouter)
          in HashRouter (created by WrapperComponent)
          in WrapperComponent
```

**Comment by Loque-** [comment]
Where did you see that warning @gavinorland?

**Comment by gavinorland** [comment]
That's in the console when running `yarn test`.

**Comment by Loque-** [comment]
Ah, it's the old, error from emotionjs, Steve asked me to make the change, but based off this feedback I might have another suggestion

**Comment by gavinorland** [comment]
This is now resolved by https://github.com/stevesims/govuk-frederic/pull/42 (now merged) - but there's a tiny improvement made above to the children check!

**Comment by Loque-** [comment]
Stale and is fixed better with shouldForwardProps

**Pull request closed without merging**
