### PR TITLE
Feature/page navigation

### PR DESCRIPTION
**Pull request by Loque-**
A page navigation component with space for navigation items

screen shot 2018-10-22 at 14 18 28

**Checklist**:

* [x] Documentation
* [x] Tests
* [x] Ready to be merged

### CODE REVIEW

**Comment by penx** [comment]
Please support how an active nav item would be specified and displayed.

Possibly not a contender for context api as we'd probably expect something further up to be managing the routing and telling us what is active. But worth a thought.

**Comment by penx** [comment]
I first wrote an `asAnchor` HOC on the `Anchor` component. It seems this pattern has been repeated but kept the name `asAnchor`.

This should be uniquely named, e.g. `asPageNavigationItem` so that it can be exported from `govuk-frederic`, along with the associated `PageNavigationItem` component

**Comment by Loque-** [comment]
Great point, I hadn't considered exporting them - I wonder if it is worth scoping it to PageNavigation, something like; `PageNavigation.asAnchor`?

**Comment by penx** [comment]
derp mistaken, asAnchor was in @govuk-react/hocs, not linked to a specific component... but I think it /should/ be  😀

Thinking something along the lines of, for any component that we want to support 'as', as an interim measure until support is in Emotion:

```
import styled from 'react-emotion';

const asMyComponent = (MyComponentType) =>
  styled(MyComponentType)({
    textDecoration: 'blink',
    // etc
  });

const MyComponent = asMyComponent('a');
MyComponent.as = asMyComponent;

export default MyComponent;
```

**Comment by penx** [comment]
Or as per this comment:
https://github.com/emotion-js/emotion/issues/837#issuecomment-418886736

```jsx
export const Heading = styled(({
  as: T = 'h1',
  ...props
}) => <T {...props}/>)({
    color: 'purple',
    fontSize: '24px',
})
```

**Pull request merged**
